#!/usr/bin/env python3
import sys
from pathlib import Path

from clients.langgraph_agent.k8s_agent import State
from windowed_file import WindowedFile  # type: ignore


def create(state: State, path: str):
    path = Path(path)
    if path.exists():
        print(f"Warning: File '{path}' already exists.")
        return 1

    path.write_text("\n")

    wfile = WindowedFile(path=path)
    wfile.first_line = 0
    wfile.print_window()
